/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "primes.h"

prime_result *
find_primes_1_svc(prime_request *argp, struct svc_req *rqstp)
{
	static prime_result  result;

	/*
	 * insert server code here
	 */

	return &result;
}
